import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">EKYCBegin</Link>
        </li>
        <li>
          <Link to="/ekycintroductionstepone">EKYCIntroductionStepOne</Link>
        </li>
        <li>
          <Link to="/ekycscanidcard">EKYCScanIDCard</Link>
        </li>
        <li>
          <Link to="/ekycscanidcardaddimage">EKYCScanIDCardAddimage</Link>
        </li>
        <li>
          <Link to="/ekycintroductionsteptwo">EKYCIntroductionStepTwo</Link>
        </li>
        <li>
          <Link to="/ekycscanface">EKYCScanFace</Link>
        </li>
        <li>
          <Link to="/ekycintroductionstepthree">EKYCIntroductionStepThree</Link>
        </li>
        <li>
          <Link to="/ekycconfirminformation">EKYCConfirmInformation</Link>
        </li>
        <li>
          <Link to="/ekycintroductionstepfour">EKYCIntroductionStepFour</Link>
        </li>
        <li>
          <Link to="/ekycsignature">EKYCSignature</Link>
        </li>
        <li>
          <Link to="/ekycsuccessful">EKYCSuccessful</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
